paths:
  hdf5_data: "data/hdf5/spectra.hdf5"
  fits_directory: "../../../projects/k-pop/spectra/apogee/dr17"
  checkpoints: "checkpoints/"
  tensorboard: "tensorboard/"

training:
  num_workers: 13
  batch_size: 32
  num_epochs: 100
  learning_rate: 0.01
  latent_dim: 50
  max_files: 50000
  split_ratios: [0.7, 0.2, 0.1]
  checkpoint_interval: 10  # Save checkpoints every 10 epochs

model:
  generator_layers: [256, 512, 1024, 2048, 1024, 512]
  activation_function: "ReLU"
  output_dim: 2048
