paths:
  checkpoints: "checkpoints/"
  plots: "plots/"
  latent: "latent/"

training:
  num_workers: 13
  batch_size: 10
  num_epochs: 100
  learning_rate: 0.001
  latent_learning_rate: 0.001
  latent_dim: 20
  max_files: 4000
  split_ratios: [0.8, 0.2, 0]
  checkpoint_interval: 5
  scheduler_gamma: 30
  scheduler_step_size: 0.1

model:
  generator_layers: [256, 512, 256] 
  activation_function: "LeakyReLU"
  output_dim: 8575


dataset_name: "apogee_dr17"  # or "galah" or "boss"

datasets:
  apogee_dr17:
    type: 'StellarDataset'
    path: 'data/hdf5/apogee4000.hdf5'
    fits_directory: "../../../projects/k-pop/spectra/apogee/dr17"
    max_files: 100
  galah:
    type: 'StellarDataset'
    path: 'path_to_other_data.hdf5'
    fits_directory: "../../../projects/k-pop/spectra/apogee/dr17"
    max_files: 200
  boss:
    type: 'QuasarDataset'
    path: 'path_to_other_data.hdf5'
    fits_directory: "../../../projects/k-pop/spectra/apogee/dr17"
    max_files: 200