paths:
  checkpoints: "checkpoints/"
  plots: "plots/"
  latent: "latent/"

training:
  num_workers: 2
  batch_size: 5
  num_epochs: 50
  learning_rate: 0.001
  latent_learning_rate: 0.001
  latent_dim: 20
  max_files: 1900
  split_ratios: [0.8, 0.2, 0]
  checkpoint_interval: 5
  scheduler_gamma: 30
  scheduler_step_size: 0.1
  n_samples_per_spectrum: 7000
  validation_split: 0.2
  n_subspectra: 2

model:
  generator_layers: [24, 256, 512, 256] 
  activation_function: "LeakyReLU"
  # output_dim: 31225 #### for interpolation
  # output_dim: 26000
  output_dim: 31225
  max_wavelength: 17500
  pe_dim: 4
  


dataset_name: "combined"  # or "galah" or "boss"

datasets:
  apogee_dr17:
    type: 'StellarDataset'
    path: 'data/hdf5/apogee4000.hdf5'
    fits_directory: "../../../projects/k-pop/spectra/apogee/dr17"
    max_files: 100
  galah:
    type: 'StellarDataset'
    path: 'path_to_other_data.hdf5'
    fits_directory: "../../../projects/k-pop/spectra/apogee/dr17"
    max_files: 200
  boss:
    type: 'QuasarDataset'
    path: 'path_to_other_data.hdf5'
    fits_directory: "../../../projects/k-pop/spectra/apogee/dr17"
    max_files: 200
  combined:
    type: 'combinedDataset'
    path: 'data/healpixfiles_inter'
    file_path: 'data/healpixfiles_inter/spectra_healpix_170.hdf5'
