paths:
  hdf5_data: "data/hdf5/spectra500.hdf5"
  fits_directory: "../../../projects/k-pop/spectra/apogee/dr17"
  checkpoints: "checkpoints/"
  plots: "plots/"
  tensorboard: "tensorboard/"

training:
  num_workers: 10
  batch_size: 10
  num_epochs: 100
  learning_rate: 0.001
  latent_dim: 5
  max_files: 500
  split_ratios: [0.7, 0.2, 0.1]
  checkpoint_interval: 10  # Save checkpoints every 10 epochs

model:
  generator_layers: [256, 512, 1024, 512] ## was [256, 512, 1024, 2048, 1024, 512]
  activation_function: "LeakyReLU"
  output_dim: 8575
